events {
    worker_connections  1024;  ## Default: 1024
}
http {
    server {
        listen 80; ##Слушаем 80 порт
        location / {
            proxy_pass http://em_backend:8080; ##Proxy_pass на backend-сервис
            proxy_set_header Host $host;  ##Дефолтный конфиг
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}